server:
  port: 10087


spring:
  application:
    name: democlientconsumer


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


